### ISSUE TITLE
Feature request: schema validation

### ISSUE THREAD

**Issue by MrSeccubus** [mprpic/cvelint#4]
CVE json files have a well defined schema. Can you check agains this schema?

**Comment by andrewpollock** [comment]
IMO, linting is doing different things to outright schema validation. In theory, step zero is to pass schema validation, step 1 is to be lint-clean for things the schema either cannot (or is not currently) validating.

There's existing tooling to check JSON input validates against its schema, why not just use that? Do one thing and do it well...

**Comment by MrSeccubus** [comment]
The purpose of a linter is to declare code clean (lint free). It acts as a super checker for code. Flagging things the compiler will and will not catch. 

If I run C code with a syntax error through a linter I expect it to fail. If code passes the linter I expect it to compile. 

Similarly if a CVE JSON file is declared lint free I expect it to be valid and accepted by the CVE service and thus to adhere to the schema.

**Comment by MrSeccubus** [comment]
There are standard json schema validation libraries like https://pkg.go.dev/github.com/santhosh-tekuri/jsonschema/v5 that should do the job.

**Comment by mprpic** [comment]
@MrSeccubus since your CNA bot already depends on cvelib, and cvelib offers schema validation against its own set of schema files (see https://github.com/RedHatProductSecurity/cvelib/tree/master/cvelib/schemas), I too think it might be duplicative to replicate that same functionality in cvelint.
