### ISSUE TITLE
Discussion: three checks I have in cna-bot that might belong in cvelint too

### ISSUE THREAD

**Issue by MrSeccubus** [mprpic/cvelint#8]
I cross checked the checks I have in cna-bot with those in cvelint.

So definitly only belong in cnabot, but three migth belong in cvelint as well.

I check if a cve record at least has one refrences. Reson behind this, if there are no references, then the CVE record is the only reference which is against CNA policy (public but not published)

I als check if references are tagged. I think it is good practise to at least tag references, but it is not stated as a requirement in the schema.

I also think it would be good for at least one check to be tagged as a (vendor) advisory, but again it oes not state this anywhere.

**Comment by mprpic** [comment]
Every CVE record should have at least one reference, it's required by the schema even:

https://github.com/CVEProject/cve-schema/blob/5.0.1/schema/v5.0/CVE_JSON_5.0_schema.json#L812

Tagging is definitely optional but we could add it as a warning-level check, same with a reference tagged as a vendor advisory.

**Comment by MrSeccubus** [comment]
For a research CNA ( like DIVD) a vendor-advisory is optional.

**Comment by mprpic** [comment]
Looking back at this, I think this won't work as a warning either, more like a suggestion. Tagging is not required for references and I also don't see anything that would depend on it, so it's hard to flag this as anything but a recommendation. But then that would apply just the same to almost any other field that is not required by the schema.
